# This is a basic workflow to help you get started with Actions

name: Build Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  render-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"
      
      - name: Get and install Hugo
        run: |
          mkdir $HOME/src
          cd $HOME/src
          git clone https://github.com/gohugoio/hugo.git
          cd hugo
          go install
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
